# Remember, yaml doesn't use tabs; only spaces
filepaths:
  # Does not need a user variable
  input_directory: "self.CWD_PATH+'/data/input/'"
  output_directory: "self.CWD_PATH+'/data/output/'"
factions:
  all_factions: "['Cortex', 'Armada', 'Legion']"
  normal_factions: "['Cortex', 'Armada']"
factories:
  all_factories: "['air', 'bot', 'hovercraft', 'vehicle', 'navy']"
  land_factories: "['air', 'bot', 'hovercraft', 'vehicle']"